export const SIGN_UP_SUCCESS = 'SIGNUPSUCCESS';
export const SIGN_IN_SUCCESS = 'SIGNINSUCCESS';
export const GET_NOTES = "GETNOTES";
export const ADD_NOTE_SUCCESS = "ADDNOTESUCCESS";
export const DELETE_NOTE_SUCCESS = "DELETENOTESUCCESS";
export const UPDATE_NOTE_SUCCESS = "UPDATE_NOTE_SUCCESS";
export const GET_NOTE_SUCCESS = "GET_NOTE_SUCCESS";